### ISSUE TITLE
Serializing a struct with a single `[u8; N]` field panics

### ISSUE THREAD

**Issue by udoprog** [facet-rs/facet#768]
While adding facet to [musli `tests`](https://github.com/udoprog/musli/pull/277), the following was discovered:

Trying to serialize the following with facet from git (using `facet-json`):

```rust
#[derive(facet::Facet)]
pub struct Packed {
    _pad0: [u8; 1],
}
```

Results in the following panic:

<details>
<summary>Panic with backtrace</summary>

```text
thread 'main' panicked at /home/udoprog/.cargo/git/checkouts/facet-2961151dee48b078/fd9ce8a/facet-serialize/src/lib.rs:433:34:
called `Result::unwrap()` on an `Err` value: ReflectError(Wrong shape: expected list, array or slice, but got Packed)
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/panicking.rs:75:14
   2: core::result::unwrap_failed
             at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/result.rs:1704:5
   3: core::result::Result<T,E>::unwrap
             at /home/udoprog/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1109:23
   4: facet_serialize::serialize_iterative
             at /home/udoprog/.cargo/git/checkouts/facet-2961151dee48b078/fd9ce8a/facet-serialize/src/lib.rs:431:50
   5: facet_json::serialize::peek_to_writer
             at /home/udoprog/.cargo/git/checkouts/facet-2961151dee48b078/fd9ce8a/facet-json/src/serialize.rs:34:5
   6: facet_json::serialize::to_writer
             at /home/udoprog/.cargo/git/checkouts/facet-2961151dee48b078/fd9ce8a/facet-json/src/serialize.rs:25:5
   7: tests::utils::full::facet_json::State::encode::encode
             at ./tests/src/utils/full.rs:382:9
   8: tests::utils::full::facet_json::State::encode
             at ./tests/src/utils/full.rs:349:1
   9: tests::main
             at ./tests/src/main.rs:380:5
  10: core::ops::function::FnOnce::call_once
             at /home/udoprog/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

**Comment by ThouCheese** [comment]
Ah yeah I see, will give this a quick go

**Comment by ThouCheese** [comment]
Fixed in #721

**Comment by udoprog** [comment]
I'm still seeing the error when running from git:

```sh
git clone https://github.com/udoprog/musli -b facet-json musli-facet-json
cd musli-facet-json
RUST_BACKTRACE=1 cargo run --bin tests --features facet-json -- packed --iter 1
```

<details>
<summary>Backtrace</summary>

```text
thread 'main' panicked at /home/udoprog/.cargo/git/checkouts/facet-2961151dee48b078/fd9ce8a/facet-serialize/src/lib.rs:433:34:
called `Result::unwrap()` on an `Err` value: ReflectError(Wrong shape: expected list, array or slice, but got Packed)
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/panicking.rs:75:14
   2: core::result::unwrap_failed
             at /rustc/17067e9ac6d7ecb70e50f92c1944e545188d2359/library/core/src/result.rs:1704:5
   3: core::result::Result<T,E>::unwrap
             at /home/udoprog/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1109:23
   4: facet_serialize::serialize_iterative
             at /home/udoprog/.cargo/git/checkouts/facet-2961151dee48b078/fd9ce8a/facet-serialize/src/lib.rs:431:50
   5: facet_json::serialize::peek_to_writer
             at /home/udoprog/.cargo/git/checkouts/facet-2961151dee48b078/fd9ce8a/facet-json/src/serialize.rs:34:5
   6: facet_json::serialize::to_writer
             at /home/udoprog/.cargo/git/checkouts/facet-2961151dee48b078/fd9ce8a/facet-json/src/serialize.rs:25:5
   7: tests::utils::full::facet_json::State::encode::encode
             at ./tests/src/utils/full.rs:382:9
   8: tests::utils::full::facet_json::State::encode
             at ./tests/src/utils/full.rs:349:1
   9: tests::main
             at ./tests/src/main.rs:380:5
  10: core::ops::function::FnOnce::call_once
             at /home/udoprog/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
```
</details>

**Comment by ThouCheese** [comment]
Yeah I mistyped the number oops its #769

**Comment by ThouCheese** [comment]
This is now merged
